### ISSUE TITLE
Can run second container but doesnt allow 2FA code to be input

### ISSUE THREAD

**Issue by eldudemeister** [boredazfcuk/docker-icloud_photos_downloader#5]
I can run both docker containers but when I run the second, it doesnt allow me to input the code from my iphone. I don't get the option to press 0 or 1. It basically just says cookie is generated and sync should be successful but the cookie doesnt appear in the file...

**Comment by boredazfcuk** [comment]
Hi, I've replicated this and it should now be fixed.

I've pushed a new version to Github which should trigger a rebuild on Dockerhub if you'd pulled the image from there. Unfortunately, I ran an script I made to push my changes, but it's pushed changes to all of my containers. It might take a day or so before Dockerhub finishes building them all!

**Comment by eldudemeister** [comment]
Hi, sorry I’m still having the same issue. I’ve pulled the latest image from docker hub and it still authenticates without me entering in the code and doesn’t save the cookie. Can I help with any debugging?

**Comment by boredazfcuk** [comment]
Can you run the container interactively, but with your correct details:

```
docker run -it --rm \
 --network containers \
 --env USER=boredazfcuk \
 --env UID=1000 \
 --env GROUP=admins \
 --env GID=1010 \
 --env APPLEID="me@email.com" \
 --env APPLEPASSWORD="mepasswd" \
 --volume icloudpd_boredazfcuk_config:/config \
 --user 1000:1010 \
 boredazfcuk/icloudpd /bin/ash
```

Then run the command to generate the cookie:
```
/usr/bin/icloudpd --username "${APPLEID}" --password "${APPLEPASSWORD}" --cookie-directory "${CONFIGDIR}"
```
If it errors out here, it will show you what the error is.

If a cookie already exists for your e-mail address, it will need to be removed first.

**Comment by boredazfcuk** [comment]
Just out of curiosity, your password doesn't container special characters like $ or " or ' or \ by any chance?

**Comment by eldudemeister** [comment]
Thanks for this, no, no special characters in my password. I think I've found the issue. 
`2020-01-04 08:40:12 DEBUG    Authenticating...
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.4.4', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.4.4-py3.8.egg/icloudpd/base.py", line 238, in main
  File "/usr/lib/python3.8/site-packages/icloudpd-1.4.4-py3.8.egg/icloudpd/authentication.py", line 29, in authenticate
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 223, in authenticate
    self.session.cookies.save()
  File "/usr/lib/python3.8/http/cookiejar.py", line 1890, in save
    with open(filename, "w") as f:
PermissionError: [Errno 13] Permission denied: '/config/mattbridgesmecom'
/ $
`
Looks like a permission issue?

**Comment by eldudemeister** [comment]
Corrected the permission issue and was able to generate the cookie as expected and it all went through. Below is the error message:
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.4.4', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.4.4-py3.8.egg/icloudpd/base.py", line 277, in main
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Hopefully this helps?

**Comment by boredazfcuk** [comment]
> 
> 
> Corrected the permission issue and was able to generate the cookie as expected and it all went through. Below is the error message:
> File "/usr/bin/icloudpd", line 11, in
> load_entry_point('icloudpd==1.4.4', 'console_scripts', 'icloudpd')()
> File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 722, in **call**
> return self.main(*args, **kwargs)
> File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 697, in main
> rv = self.invoke(ctx)
> File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 895, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/lib/python3.8/site-packages/click-6.7-py3.8.egg/click/core.py", line 535, in invoke
> return callback(*args, **kwargs)
> File "/usr/lib/python3.8/site-packages/icloudpd-1.4.4-py3.8.egg/icloudpd/base.py", line 277, in main
> File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
> path = os.fspath(path)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> Hopefully this helps?

That's great thanks. I've set the function that configures permissions to run after the user account is created (so now it runs before the cookie creation function). This should fix the issue for any new installations.

The reason you see the error after you generated the cookie is because the python code that generates the cookie is buggy. It always happens when the cookie is already in place which is why why I silence the error output in my container.

It should start pulling all your photos now though.

**Comment by eldudemeister** [comment]
Thanks so much for the help. I’m getting a destination volume not mounted now. I’ve created a folder under homes/Matt/iCloud and this is the folder in the create command I use. I know it’s going to be a silly error but I don’t suppose you could point me in the right direction?

**Comment by boredazfcuk** [comment]
Hi, that's a failsafe I stuck in there to prevent it from re-downloading your entire photostream if the volume underneath isn't mounted for some reason. It happened to me when my /home volume didn't mount and it filled up my root volume. Check here:

[Volume Configuration](https://github.com/boredazfcuk/docker-icloud_photos_downloader#volume-configuration)

**Comment by eldudemeister** [comment]
Thanks, I'm still struggling with the destination volume not mounting, I've pasted the create command I'm using below and wondered if you could just confirm it is correct. Sensitive info removed. I wondered whether the command should be volume /home/matt/iCloud:/iCloud so that it mimicks the config volume mount? I've also created the iCloud folder manually in my user home folder so struggling to see why it isnt mounting? Thanks for all the help!


docker create --name icloudpd --hostname icloudpd --network docker_default --restart=always --env USER=matt --env UID=1000 --env GROUP=admins --env GID=1000 --env APPLEID=email --env APPLEPASSWORD=password --env AUTHTYPE=2FA --env SETDATETIMEEXIF=True --env INTERVAL=21600 --env TZ=Europe/London --volume /home/matt/docker/iCloudpd/config:/config --volume /home/matt/iCloud:/home/matt/iCloud boredazfcuk/icloudpd

**Comment by boredazfcuk** [comment]
Okey doke... so, from the look of things you want to download your photo stream to the /home/matt/iCloud directory.

Firstly, make sure the iCloudPD container isn't running and then open up a terminal window as your user (not root) and then enter the commands:
```
mkdir -p ~/iCloud
touch ~/iCloud/.mounted
```

Then fire up the container again. This should now find the fail-safe file and start downloading your photo stream.

**Comment by eldudemeister** [comment]
That's done it! Thank you so much for bearing with me!

**Comment by boredazfcuk** [comment]
Awesome. Glad you sorted it in the end
